
#  （land 是系统数据源的名称）
spring:
  datasource:
    driver-class-name: sun.jdbc.odbc.JdbcOdbcDriver
    url: jdbc:odbc:land
    tomcat:
      connection-properties: charSet=gbk
  main:
    banner-mode: off
